### ISSUE TITLE
Annotations in read-only buffers

### ISSUE THREAD

**Issue by indigoviolet** [bastibe/annotate.el#101]
I originally wrote this as a comment here: https://github.com/bastibe/annotate.el/issues/74#issuecomment-820828751, but I noticed a couple of related bugs so wanted to call it out into its own issue.

1) Clearing annotations from a read only buffer does not work for me

2) `annotate-summary-of-file-from-current-pos` gets out of sync if I delete an annotation for a read-only buffer (ie. it doesn't get deleted from the buffer itself).

Thank you for this library!

**Comment by cage2** [comment]
Hi!

You spotted two new bugs, thanks!

The first is interesting too!

To be honest `annotate-summary-of-file-from-current-pos` was kind of an hack and needs to be inspected and tested a bit more because i suspect there are more problems hiding in that part of the code.

I think i can starts working on these bugs next weeks unfortunately because of some stuff i have to deal with.

Bye!
C.

**Comment by indigoviolet** [comment]
Thanks for the response. No rush, this is not a deal breaker.

**Comment by cage2** [comment]
Hi!

the first has been fixed in #102

Bye!
C.

**Comment by cage2** [comment]
Hi!

Also item number 2 should be fixed in #102 

Bye!!
C.

**Comment by cage2** [comment]
Fixed in #102
