### ISSUE TITLE
Org mode: Annotations lose their position when subtrees are moved

### ISSUE THREAD

**Issue by matbra** [bastibe/annotate.el#26]
Hi, @bastibe !

It seems that moving subtrees in org mode (e.g. calling `(org-move-subtree-up)` or `(org-move-subtree-down)`) messes up the positions of annotations. Unfortunately, I was not able to figure out what causes the problem yet. I will be looking into this but just wanted to let you know. Maybe you already have an idea for solving this.

Just let me know if you need further information...

Greetings

Matthias

**Comment by bastibe** [comment]
The annotations are attached to the text as overlays. If org-mode moves a subtree but not it's overlays, there's not much we can do.

That being said, `org-move-subtree-down` uses `buffer-substring` to copy the subtree, which does copy all text properties, but apparently doesn't copy the overlays. Maybe there is a way to rewrite annotate.el to use properties instead of overlays.

This is not something I have the time to do right now, but If you want to take a stab at it, I'd be happy to review and merge it.

**Comment by matbra** [comment]
Okay - thanks for the information. At the moment I'm also pretty short of time but I'm curious to take a closer look at `annotate.el`and will have a try when I have the time.

**Comment by bastibe** [comment]
I'm closing this for now. Please reopen if you think it's important.
